# Copyright (C) 2013 Sony Mobile Communication
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http:system///www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#### THE FILE IS GENERATED BY SCRIPT SO DO NOT MODIFY IT MANUALLY! ####

PRODUCT_COPY_FILES += \
    vendor/sony/c1905/proprietary/root/sbin/wait4tad_static:root/sbin/wait4tad_static \
    vendor/sony/c1905/proprietary/root/sbin/tad_static:root/sbin/tad_static \
    vendor/sony/c1905/proprietary/lib/libCB.so:system/lib/libCB.so \
    vendor/sony/c1905/proprietary/lib/libchromatix_s5k4e1_2nd_default_video_1.so:system/lib/libchromatix_s5k4e1_2nd_default_video_1.so \
    vendor/sony/c1905/proprietary/lib/libchromatix_s5k4e1_2nd_preview.so:system/lib/libchromatix_s5k4e1_2nd_preview.so \
    vendor/sony/c1905/proprietary/lib/libchromatix_s5k4e1_2nd_preview_1.so:system/lib/libchromatix_s5k4e1_2nd_preview_1.so \
    vendor/sony/c1905/proprietary/lib/libchromatix_s5k4e1_default_video.so:system/lib/libchromatix_s5k4e1_default_video.so \
    vendor/sony/c1905/proprietary/lib/libchromatix_s5k4e1_default_video_1.so:system/lib/libchromatix_s5k4e1_default_video_1.so \
    vendor/sony/c1905/proprietary/lib/libchromatix_s5k4e1_preview.so:system/lib/libchromatix_s5k4e1_preview.so \
    vendor/sony/c1905/proprietary/lib/libchromatix_s5k4e1_preview_1.so:system/lib/libchromatix_s5k4e1_preview_1.so \
    vendor/sony/c1905/proprietary/lib/libcredential-manager-service.so:system/lib/libcredential-manager-service.so \
    vendor/sony/c1905/proprietary/lib/libQSEEComAPI.so:system/lib/libQSEEComAPI.so \
    vendor/sony/c1905/proprietary/lib/libqdi.so:system/lib/libqdi.so \
    vendor/sony/c1905/proprietary/lib/libsc-a3xx.so:system/lib/libsc-a3xx.so \
    vendor/sony/c1905/proprietary/lib/libc2d2_z180.so:system/lib/libc2d2_z180.so \
    vendor/sony/c1905/proprietary/lib/libmmcamera_plugin.so:system/lib/libmmcamera_plugin.so \
    vendor/sony/c1905/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/sony/c1905/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/sony/c1905/proprietary/lib/libtime_genoff.so:system/lib/libtime_genoff.so \
    vendor/sony/c1905/proprietary/lib/libtzplayready.so:system/lib/libtzplayready.so \
    vendor/sony/c1905/proprietary/lib/libfastcvopt.so:system/lib/libfastcvopt.so \
    vendor/sony/c1905/proprietary/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
    vendor/sony/c1905/proprietary/lib/libmorpho_easy_hdr.so:system/lib/libmorpho_easy_hdr.so \
    vendor/sony/c1905/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/sony/c1905/proprietary/lib/libdrmfs.so:system/lib/libdrmfs.so \
    vendor/sony/c1905/proprietary/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
    vendor/sony/c1905/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/sony/c1905/proprietary/lib/libmmcamera_3a_legacy.so:system/lib/libmmcamera_3a_legacy.so \
    vendor/sony/c1905/proprietary/lib/libmorpho_scene_detector.so:system/lib/libmorpho_scene_detector.so \
    vendor/sony/c1905/proprietary/lib/libmorpho_posture_detect.so:system/lib/libmorpho_posture_detect.so \
    vendor/sony/c1905/proprietary/lib/libc2d2_a3xx.so:system/lib/libc2d2_a3xx.so \
    vendor/sony/c1905/proprietary/lib/libdrmdiag.so:system/lib/libdrmdiag.so \
    vendor/sony/c1905/proprietary/lib/lib_dlb_msd.so:system/lib/lib_dlb_msd.so \
    vendor/sony/c1905/proprietary/lib/liblights-core.so:system/lib/liblights-core.so \
    vendor/sony/c1905/proprietary/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
    vendor/sony/c1905/proprietary/lib/libdivxdrmdecrypt.so:system/lib/libdivxdrmdecrypt.so \
    vendor/sony/c1905/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/sony/c1905/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/sony/c1905/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/sony/c1905/proprietary/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
    vendor/sony/c1905/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/sony/c1905/proprietary/lib/egl/libGLESv2S3D_adreno200.so:system/lib/egl/libGLESv2S3D_adreno200.so \
    vendor/sony/c1905/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
    vendor/sony/c1905/proprietary/lib/libprofiler_msmadc.so:system/lib/libprofiler_msmadc.so \
    vendor/sony/c1905/proprietary/lib/libOpenCL.so:system/lib/libOpenCL.so \
    vendor/sony/c1905/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
    vendor/sony/c1905/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/sony/c1905/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/sony/c1905/proprietary/lib/libmmcamera_image_stab.so:system/lib/libmmcamera_image_stab.so \
    vendor/sony/c1905/proprietary/lib/libcsd-client.so:system/lib/libcsd-client.so \
    vendor/sony/c1905/proprietary/lib/hw/vendor-camera.msm8960.so:system/lib/hw/vendor-camera.msm8960.so \
    vendor/sony/c1905/proprietary/lib/hw/gps.msm8960.so:system/lib/hw/gps.msm8960.so \
    vendor/sony/c1905/proprietary/lib/hw/sensors.msm8960.so:system/lib/hw/sensors.msm8960.so \
    vendor/sony/c1905/proprietary/lib/hw/nfc.msm8960.so:system/lib/hw/nfc.msm8960.so \
    vendor/sony/c1905/proprietary/lib/hw/vendor-lights.msm8960.so:system/lib/hw/vendor-lights.msm8960.so \
    vendor/sony/c1905/proprietary/lib/libdrmtime.so:system/lib/libdrmtime.so \
    vendor/sony/c1905/proprietary/lib/libI420colorconvert.so:system/lib/libI420colorconvert.so \
    vendor/sony/c1905/proprietary/lib/libOpenVG.so:system/lib/libOpenVG.so \
    vendor/sony/c1905/proprietary/lib/libqmi_client_qmux.so:system/lib/libqmi_client_qmux.so \
    vendor/sony/c1905/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
    vendor/sony/c1905/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
    vendor/sony/c1905/proprietary/lib/libqmi_encdec.so:system/lib/libqmi_encdec.so \
    vendor/sony/c1905/proprietary/lib/libmorpho_image_stabilizer3.so:system/lib/libmorpho_image_stabilizer3.so \
    vendor/sony/c1905/proprietary/lib/libmm-audio-resampler.so:system/lib/libmm-audio-resampler.so \
    vendor/sony/c1905/proprietary/lib/libmmcamera_tintless_wrapper.so:system/lib/libmmcamera_tintless_wrapper.so \
    vendor/sony/c1905/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/sony/c1905/proprietary/lib/libqcci_legacy.so:system/lib/libqcci_legacy.so \
    vendor/sony/c1905/proprietary/lib/libC2D2.so:system/lib/libC2D2.so \
    vendor/sony/c1905/proprietary/lib/libdrmdecrypt.so:system/lib/libdrmdecrypt.so \
    vendor/sony/c1905/proprietary/lib/libmorpho_hdr_checker.so:system/lib/libmorpho_hdr_checker.so \
    vendor/sony/c1905/proprietary/lib/libmiscta.so:system/lib/libmiscta.so \
    vendor/sony/c1905/proprietary/lib/libmmcamera_wavelet_lib.so:system/lib/libmmcamera_wavelet_lib.so \
    vendor/sony/c1905/proprietary/lib/libqmi_common_so.so:system/lib/libqmi_common_so.so \
    vendor/sony/c1905/proprietary/lib/libqcci_adc.so:system/lib/libqcci_adc.so \
    vendor/sony/c1905/proprietary/lib/libmmcamera_hdr_lib.so:system/lib/libmmcamera_hdr_lib.so \
    vendor/sony/c1905/proprietary/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
    vendor/sony/c1905/proprietary/lib/libgemini.so:system/lib/libgemini.so \
    vendor/sony/c1905/proprietary/lib/libgps.utils.so:system/lib/libgps.utils.so \
    vendor/sony/c1905/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/sony/c1905/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/sony/c1905/proprietary/lib/libqmi_csi.so:system/lib/libqmi_csi.so \
    vendor/sony/c1905/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/sony/c1905/proprietary/lib/libqmi_cci.so:system/lib/libqmi_cci.so \
    vendor/sony/c1905/proprietary/lib/libsurround_proc.so:system/lib/libsurround_proc.so \
    vendor/sony/c1905/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/sony/c1905/proprietary/lib/libadsprpc.so:system/lib/libadsprpc.so \
    vendor/sony/c1905/proprietary/lib/libdl.so:system/lib/libdl.so \
    vendor/sony/c1905/proprietary/lib/libta.so:system/lib/libta.so \
    vendor/sony/c1905/proprietary/lib/libkeyctrl.so:system/lib/libkeyctrl.so \
    vendor/sony/c1905/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/sony/c1905/proprietary/lib/libmmcamera_interface2.so:system/lib/libmmcamera_interface2.so \
    vendor/sony/c1905/proprietary/lib/libmorpho_denoiser.so:system/lib/libmorpho_denoiser.so \
    vendor/sony/c1905/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
    vendor/sony/c1905/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/sony/c1905/proprietary/lib/libface.so:system/lib/libface.so \
    vendor/sony/c1905/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
    vendor/sony/c1905/proprietary/lib/libmmcamera_tintless_algo.so:system/lib/libmmcamera_tintless_algo.so \
    vendor/sony/c1905/proprietary/lib/libgsl.so:system/lib/libgsl.so \
    vendor/sony/c1905/proprietary/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
    vendor/sony/c1905/proprietary/lib/libloc_adapter.so:system/lib/libloc_adapter.so \
    vendor/sony/c1905/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/sony/c1905/proprietary/lib/libloc_eng.so:system/lib/libloc_eng.so \
    vendor/sony/c1905/proprietary/lib/libmercury.so:system/lib/libmercury.so \
    vendor/sony/c1905/proprietary/lib/libmm-abl.so:system/lib/libmm-abl.so \
    vendor/sony/c1905/proprietary/lib/librmp.so:system/lib/librmp.so \
    vendor/sony/c1905/proprietary/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
    vendor/sony/c1905/proprietary/lib/libmmcamera_statsproc31.so:system/lib/libmmcamera_statsproc31.so \
    vendor/sony/c1905/proprietary/etc/firmware/dxhdcp2.b00:system/etc/firmware/dxhdcp2.b00 \
    vendor/sony/c1905/proprietary/etc/firmware/dxhdcp2.b01:system/etc/firmware/dxhdcp2.b01 \
    vendor/sony/c1905/proprietary/etc/firmware/dxhdcp2.b02:system/etc/firmware/dxhdcp2.b02 \
    vendor/sony/c1905/proprietary/etc/firmware/dxhdcp2.b03:system/etc/firmware/dxhdcp2.b03 \
    vendor/sony/c1905/proprietary/etc/firmware/dxhdcp2.mdt:system/etc/firmware/dxhdcp2.mdt \
    vendor/sony/c1905/proprietary/etc/firmware/dxhdcp2.flist:system/etc/firmware/dxhdcp2.flist \
    vendor/sony/c1905/proprietary/etc/firmware/vidc.mdt:system/etc/firmware/vidc.mdt \
    vendor/sony/c1905/proprietary/etc/firmware/tzlibasb.mdt:system/etc/firmware/tzlibasb.mdt \
    vendor/sony/c1905/proprietary/etc/firmware/tzlibasb.b02:system/etc/firmware/tzlibasb.b02 \
    vendor/sony/c1905/proprietary/etc/firmware/tzsuntory.b01:system/etc/firmware/tzsuntory.b01 \
    vendor/sony/c1905/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    vendor/sony/c1905/proprietary/etc/firmware/vidcfw.elf:system/etc/firmware/vidcfw.elf \
    vendor/sony/c1905/proprietary/etc/firmware/tzlibasb.flist:system/etc/firmware/tzlibasb.flist \
    vendor/sony/c1905/proprietary/etc/firmware/tzsuntory.b00:system/etc/firmware/tzsuntory.b00 \
    vendor/sony/c1905/proprietary/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
    vendor/sony/c1905/proprietary/etc/firmware/tzlibasb.b01:system/etc/firmware/tzlibasb.b01 \
    vendor/sony/c1905/proprietary/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
    vendor/sony/c1905/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    vendor/sony/c1905/proprietary/etc/firmware/vidc.b00:system/etc/firmware/vidc.b00 \
    vendor/sony/c1905/proprietary/etc/firmware/tzsuntory.mdt:system/etc/firmware/tzsuntory.mdt \
    vendor/sony/c1905/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    vendor/sony/c1905/proprietary/etc/firmware/cyttsp_8064_mtp.hex:system/etc/firmware/cyttsp_8064_mtp.hex \
    vendor/sony/c1905/proprietary/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
    vendor/sony/c1905/proprietary/etc/firmware/vidc.b02:system/etc/firmware/vidc.b02 \
    vendor/sony/c1905/proprietary/etc/firmware/vidc.b03:system/etc/firmware/vidc.b03 \
    vendor/sony/c1905/proprietary/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
    vendor/sony/c1905/proprietary/etc/firmware/cyttsp_8960_cdp.hex:system/etc/firmware/cyttsp_8960_cdp.hex \
    vendor/sony/c1905/proprietary/etc/firmware/tzsuntory.b02:system/etc/firmware/tzsuntory.b02 \
    vendor/sony/c1905/proprietary/etc/firmware/tzsuntory.b03:system/etc/firmware/tzsuntory.b03 \
    vendor/sony/c1905/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    vendor/sony/c1905/proprietary/etc/firmware/tzsuntory.flist:system/etc/firmware/tzsuntory.flist \
    vendor/sony/c1905/proprietary/etc/firmware/tzlibasb.b03:system/etc/firmware/tzlibasb.b03 \
    vendor/sony/c1905/proprietary/etc/firmware/tzlibasb.b00:system/etc/firmware/tzlibasb.b00 \
    vendor/sony/c1905/proprietary/etc/firmware/vidc.b01:system/etc/firmware/vidc.b01 \
    vendor/sony/c1905/proprietary/vendor/firmware/libpn544_fw.so:system/vendor/firmware/libpn544_fw.so \
    vendor/sony/c1905/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/sony/c1905/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/sony/c1905/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/sony/c1905/proprietary/bin/efsks:system/bin/efsks \
    vendor/sony/c1905/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/sony/c1905/proprietary/bin/qrngd:system/bin/qrngd \
    vendor/sony/c1905/proprietary/bin/updatemiscta:system/bin/updatemiscta \
    vendor/sony/c1905/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/sony/c1905/proprietary/bin/rild:system/bin/rild \
    vendor/sony/c1905/proprietary/bin/thermald:system/bin/thermald \
    vendor/sony/c1905/proprietary/bin/taimport:system/bin/taimport \
    vendor/sony/c1905/proprietary/bin/ta_qmi_service:system/bin/ta_qmi_service \
    vendor/sony/c1905/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/sony/c1905/proprietary/bin/ks:system/bin/ks \
    vendor/sony/c1905/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/sony/c1905/proprietary/bin/led_deamon:system/bin/led_deamon
